### ISSUE TITLE
Changing Feeds (and page load) takes >10 seconds to load articles

### ISSUE THREAD

**Issue by ceasley** [tt-rss/tt-rss#190]
### What is the problem?

After recent updates, I have noticed TT-RSS will load (with the spinner icon) feeds for a much longer time than usual.  Browser tracing indicates backend.php is taking a very long time to return while pulling the article list.

### Reproduction Steps

Load the TT-RSS page.  The default-selected feed (fresh items) will load for 10-15 seconds before displaying any data.

### tt-rss Version

v25.11-8d7732bc

### Environment

Running the supahgreg docker containers on Debian Bookworm with the latest version of Docker.

### Other Information

I can provide a .HAR file if needed with this issue.

**Comment by ceasley** [comment]
Just to add, this looks like it might be an issue with Postgres 16 and newer versions.  I'm testing with version 15 now as a rollback test to see if the issue still exists.

EDIT: Postgres 15 loads the articles much quicker and cuts the loading time to roughly half, but it still loads slower than about a month ago.  I'll start stepping backward through commits and see if I can find which one introduced the slowness.

**Comment by supahgreg** [comment]
FWIW, I'm running PostgreSQL `18.1` (and `18.0`, etc. before that; understandably not everyone will do that) and haven't noticed any issues.

Some questions:
* I'm guessing you're seeing the slowness only with the `backend.php` calls having `op: "Feeds"` and `method: "view"` (among other things) in the request body?
* Any significant difference if you change the view mode (e.g. `Unread`) and/or sort order?
* Anything notable about the number of articles you might have (e.g. high number of unread, disabled or high threshold for purging, etc.)?
* **edit:** Does this happen regardless of feed and/or category?
  * I've occasionally noticed sites embedding large base64-encoded images, which can slow things down.  Based upon what you mentioned about PostgreSQL, however, I'm guessing this isn't what's happening.

Having a specific commit would certainly be great.  If you'd like to provide your assorted display options (e.g. view mode, sort order, combined mode, etc.) that might also help narrow things down.

**Comment by dymn** [comment]
I confirm the problem. I thought something had happened to the server, I already completely deleted and reinstalled tt-rss, but without success.
Rolling back to Postgres 15 did not help. I don't know if I did it right, but to roll back, I changed the version in docker-compose.yml and deleted the tt-rss_db volume.

**Comment by supahgreg** [comment]
@dymn If you can provide some or all of the info requested in my prior comment it might help.  At the moment I'm unable to reproduce the issue.

**edit:** Also, for anyone: identifying the last "working" commit (`sha-*` tag) would be ideal, but an approximate date of your previous update/upgrade may also help narrow things down.

**Comment by ceasley** [comment]
Alrighty, I've taken some time to test and see if I can answer your questions.  And, you are correct, the delay is in backend.php, but the method and operation are different.  In my case, the delay is with `op: "RPC"` and `method: "GetAllCounters"`

- Any significant difference if you change the view mode (e.g. Unread) and/or sort order?
_No difference, except for "Unread".  The delay seems to increase in relation to how many articles are being loaded in the view.  More articles = longer delay.  "All articles" takes the longest.  "Unread" becomes noticeably slower at ~50 articles._
- Anything notable about the number of articles you might have (e.g. high number of unread, disabled or high threshold for purging, etc.)? edit: Does this happen regardless of feed and/or category?
_See above._
- I've occasionally noticed sites embedding large base64-encoded images, which can slow things down. Based upon what you mentioned about PostgreSQL, however, I'm guessing this isn't what's happening.
_I haven't noticed any correlation with any base64 images in my feeds, but it's possible I suppose._
- Having a specific commit would certainly be great. If you'd like to provide your assorted display options (e.g. view mode, sort order, combined mode, etc.) that might also help narrow things down.
_I'm still working on the specific commit that might've caused this.  As for my settings, they are as such:_
_Combined mode with "Always Expand Articles" enabled, Adaptive for article view, and the sort order is set to the default._

**Comment by supahgreg** [comment]
Thanks for the info and testing.  I'll look into that particular call.

**Comment by supahgreg** [comment]
If you mark an article as read (or unread) there will be a `getAllCounters` request shortly after with a `feed_ids` param containing the related feed ID.  Is that request just as slow as the initial one?

If you want, the initial call can be triggered manually in the console with `Feeds.requestCounters()` and the selective call with something like `Feeds.requestCounters([123])` (where `123` is a feed ID) or `Feeds.requestCounters(null, [-1234])` (where `-1234` is a label ID).

**Comment by ceasley** [comment]
> If you want, the initial call can be triggered manually in the console with Feeds.requestCounters() and the selective call with something like Feeds.requestCounters([123]) (where 123 is a feed ID) or Feeds.requestCounters(null, [-1234]) (where -1234 is a label ID).

I'll give this a shot.

I just found when clicking another feed ("Recently read" or any other feed group really for example), the slow call DOES seem to be `op: "Feeds"` and `method: "view"`, so it may be playing a role here as well.  It just doesn't seem to be the first culprit on page load for me.

**Comment by supahgreg** [comment]
Hm, interesting...

Might be worth just jumping back to [some old tag](https://hub.docker.com/r/supahgreg/tt-rss/tags?ordering=-last_updated) (e.g. `sha-18f5979` from 2025-10-05, `sha-36f8b93` from 2025-10-22, `sha-sha-82a1f69` from 2025-11-04) to see if it's still an issue.  There haven't been any DB schema (or other incompatible) changes, so you should be able to jump between versions without issue.

(accidentally edited the wrong comment to fix the label ID earlier, sorry)

**Comment by ceasley** [comment]
Testing some of the old tags is interesting.
`sha-6830c49`: Unable to reproduce
`sha-8b95e7d`: Unable to reproduce
`sha-ce3accb`: Issue Exists

I actually tested *many* of the releases.  This took longer than I expected (hah!)

So, it appears the issue was introduced with https://hub.docker.com/layers/supahgreg/tt-rss/sha-ce3accb/images/sha256-b242bd9ae5cb71c201419ce99a3b58e3c9ee40abbefe1d8cc7aada7ecf47440f.

After rolling back to `sha-8b95e7d` I'm seeing the following errors in the system log:
`
E_USER_WARNING (512) | backend.php:162 | Refusing to invoke method getruntimeinfo of handler RPC with invalid CSRF token. 1. backend.php(162): user_error(Refusing to invoke method getruntimeinfo of handler RPC with invalid CSRF token.)  Real IP: 172.16.1.106 Forwarded For: 172.16.1.106 Forwarded Protocol: https Remote IP: 172.16.0.12 Request URI: /tt-rss/backend.php User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
`

FWIW, I've upgraded to the PostgreSQL 18.1-alpine image, and it continues to work great using `sha-8b95e7d`.

**Comment by dymn** [comment]
> [@dymn](https://github.com/dymn) If you can provide some or all of the info requested in my prior comment it might help. At the moment I'm unable to reproduce the issue.
> 
> **edit:** Also, for anyone: identifying the last "working" commit (`sha-*` tag) would be ideal, but an approximate date of your previous update/upgrade may also help narrow things down.

I'm not good familiar with docker.
The biggest delays are with feeds from the site rutor.info. For example: http://alt.rutor.info/rss.php?full=11
In second place from the website livejournal.com. For example: https://humus.livejournal.com/data/rss

The problem cannot be reproduced with the sha-8b95e7d tag and PostgreSQL-17.

**Comment by supahgreg** [comment]
Thank you both.  Looks like I got a bit overzealous with that change (and apparently didn't notice the issue due to the speed of the DNS servers I use).

I've pushed a likely fix-- please try the current `latest` (or `sha-fd34bb2` or `20251127-084739`).

**Comment by LaurentGH** [comment]
The comment I added here was about another similar issue because it still appears with Docker image v25.11-fd34bb26. I'll try to get more information before creating a separate issue.

**Comment by dymn** [comment]
> Thank you both. Looks like I got a bit overzealous with that change.
> 
> I've pushed a likely fix-- please try the current `latest` (or `sha-fd34bb2` or `20251127-084739`).

All is ok with v25.11-fd34bb26. Thank you!

Meanwhile, I tested both Firefox and Chrome - there were delays everywhere until the last commit.

**Comment by ceasley** [comment]
> Thank you both. Looks like I got a bit overzealous with that change (and apparently didn't notice the issue due to the speed of the DNS servers I use).
> 
> I've pushed a likely fix-- please try the current `latest` (or `sha-fd34bb2` or `20251127-084739`).

Confirmed, this commit seems to resolve the issue.  Thank you very much for your help!

**Comment by supahgreg** [comment]
Cool.  Thanks again for reporting the issue and troubleshooting.
